---
- name: install legacy mysql 5.7 client from trusted private repository
  become: true
  block:
    - name: add MIT signing key to keyring
      apt_key:
        keyserver: pgp.mit.edu
        id: 5072E1F5
    - name: add mysql apt repo to sources
      apt_repository:
        repo: deb http://repo.mysql.com/apt/ubuntu/ bionic mysql-5.7
    - name: install mysql package with apt
      apt:
        name: mysql-client
