---
- name: install legacy mysql 5.7 client from trusted private repository
  become: true
  vars:
    key_filename: mysql_pubkey.asc
    apt_key_dir: /etc/apt/trusted.gpg.d
  block:
    - name: copy MIT signing key to trusted keys
      copy:
        src: "{{ key_filename }}"
        dest: "{{ apt_key_dir }}"
    - name: add mysql apt repo to sources
      apt_repository:
        repo: "deb [signed-by={{ apt_key_dir }}/{{ key_filename }}] http://repo.mysql.com/apt/ubuntu/ bionic mysql-5.7"
    - name: install mysql package with apt
      apt:
        name: mysql-client
